# Generated by Django 5.2.4 on 2025-08-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="published_at",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="status",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Признак публикации"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog/image", verbose_name="Превью"
            ),
        ),
    ]
